name: Docker Image CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "main" ]
env:
  DOCKERHUB_USER: pinkbanana
  IMAGE_NAME: pinkbanana/langgenius-ce

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      shell: bash
      env:
        DOCKERHUB_USER: ${{ env.DOCKERHUB_USER }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        /bin/bash .github/workflows/build-and-push.sh
